# Generated by Django 5.2.3 on 2025-07-11 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sdggoal',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='SDGTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_number', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='projects.sdggoal')),
            ],
            options={
                'ordering': ['goal__number', 'target_number'],
                'unique_together': {('goal', 'target_number')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='sdg_targets',
            field=models.ManyToManyField(blank=True, to='projects.sdgtarget'),
        ),
        migrations.CreateModel(
            name='SDGIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_number', models.CharField(max_length=10)),
                ('indicator_number', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.sdggoal')),
            ],
            options={
                'ordering': ['indicator_number'],
                'unique_together': {('indicator_number',)},
            },
        ),
        migrations.CreateModel(
            name='SDGProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('on_track', 'On Track'), ('at_risk', 'At Risk'), ('completed', 'Completed'), ('behind_schedule', 'Behind Schedule')], default='not_started', max_length=20)),
                ('progress_percentage', models.PositiveIntegerField(default=0, help_text='Progress percentage (0-100)')),
                ('description', models.TextField(blank=True, help_text='Description of progress made')),
                ('challenges', models.TextField(blank=True, help_text='Challenges encountered')),
                ('next_steps', models.TextField(blank=True, help_text='Next steps planned')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdg_progress', to='projects.project')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.sdgtarget')),
            ],
            options={
                'ordering': ['-reported_at'],
                'unique_together': {('project', 'target')},
            },
        ),
    ]
