# Generated by Django 5.2.3 on 2025-07-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_sdggoal_description_sdgtarget_project_sdg_targets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdggoal',
            name='shortened_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
