# Generated by Django 5.2.3 on 2025-07-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_sdggoal_shortened_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdggoal',
            name='color',
            field=models.CharField(max_length=20),
        ),
    ]
