# Generated by Django 5.2.3 on 2025-06-11 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrisk',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessment', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectrisk',
            name='risk_factors',
            field=models.ManyToManyField(to='assessments.riskfactor'),
        ),
    ]
