# Generated by Django 5.2.3 on 2025-06-12 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emph_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='organization_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='focus_areas',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='motivation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='project_experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='subscribe_to_updates',
            field=models.BooleanField(default=True),
        ),
    ]
